[project]
name = "projekt1-macd"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.1",
    "notebook>=7.3.2",
    "pandas==2.2.3",
]
